# Generated by Django 4.2 on 2025-04-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='short_code',
            new_name='short_url',
        ),
    ]
